# Generated by Django 3.0.7 on 2020-08-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionSystem', '0002_auto_20200805_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='next_question',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.IntegerField(choices=[(0, 'Radio'), (1, 'CheckBox'), (2, 'Text')], default=0),
        ),
        migrations.DeleteModel(
            name='Next',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
