# Generated by Django 3.0.7 on 2020-08-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionSystem', '0007_auto_20200808_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextanswer',
            name='question',
        ),
    ]
