# Generated by Django 3.0.7 on 2020-08-08 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionSystem', '0009_nextanswer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='nextanswer',
            name='answer',
            field=models.ManyToManyField(to='QuestionSystem.Answer'),
        ),
        migrations.AlterField(
            model_name='nextanswer',
            name='next_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextanswer_requests_created', to='QuestionSystem.Question'),
        ),
        migrations.RemoveField(
            model_name='nextanswer',
            name='question',
        ),
        migrations.AddField(
            model_name='nextanswer',
            name='question',
            field=models.ManyToManyField(to='QuestionSystem.Question'),
        ),
    ]
