# Generated by Django 3.0.7 on 2020-08-08 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionSystem', '0011_auto_20200808_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionSystem.Answer'),
        ),
        migrations.AlterField(
            model_name='nextanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionSystem.Question'),
        ),
    ]
