# Generated by Django 3.0.7 on 2020-08-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionSystem', '0012_auto_20200808_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='suggestion',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
