# Generated by Django 2.1.15 on 2020-08-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionSystem', '0016_auto_20200811_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
