# Generated by Django 2.1.15 on 2020-08-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionSystem', '0018_auto_20200811_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
