# Generated by Django 3.0.7 on 2020-08-07 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionSystem', '0003_auto_20200807_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
