# Generated by Django 3.0.7 on 2020-08-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionSystem', '0004_question_q_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='exit_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
