# Generated by Django 3.0.7 on 2020-08-08 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionSystem', '0006_auto_20200807_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='next_question',
        ),
        migrations.CreateModel(
            name='NextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_question', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionSystem.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionSystem.Question')),
            ],
        ),
    ]
