# Generated by Django 3.0.7 on 2020-08-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionSystem', '0010_auto_20200808_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='nextanswer',
            name='answer',
            field=models.IntegerField(choices=[(0, 'Null')], default=0),
        ),
        migrations.RemoveField(
            model_name='nextanswer',
            name='question',
        ),
        migrations.AddField(
            model_name='nextanswer',
            name='question',
            field=models.IntegerField(choices=[(0, 'Null')], default=0),
        ),
    ]
