# Generated by Django 2.1.15 on 2020-08-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionSystem', '0019_advise_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='response_part',
            new_name='response_part_early_retirement',
        ),
        migrations.AddField(
            model_name='answer',
            name='response_part_flix',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='response_part_forsikrde',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='response_part_jaf',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='response_part_resource',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='response_part_senior_retirement',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='response_part_sygedagpenge',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
