# Generated by Django 2.1.15 on 2020-08-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200815_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=30)),
            ],
        ),
    ]
